# Generated by Django 2.1.5 on 2019-02-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('passwd', models.CharField(max_length=100)),
                ('asset', models.IntegerField(default=0)),
                ('credit', models.IntegerField(default=100)),
                ('isIndividual', models.BooleanField(default=True)),
                ('isValidated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('isValidated', models.BooleanField(default=False)),
            ],
        ),
    ]
