# Generated by Django 2.1.5 on 2019-02-10 04:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20190209_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='trade/'),
            preserve_default=False,
        ),
    ]
