# Generated by Django 2.1.5 on 2019-02-10 12:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='trade/'),
            preserve_default=False,
        ),
    ]
