# Generated by Django 2.1.5 on 2019-02-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_energyaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonCoinCcy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('close', models.FloatField()),
            ],
        ),
    ]
