# Generated by Django 2.1.5 on 2019-02-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_carboncoinccy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carboncoinccy',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
