# Generated by Django 2.1.5 on 2019-03-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0008_auto_20190219_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carboncoinccy',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
