# Generated by Django 2.1.5 on 2019-03-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0010_energyaccount_last_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='energyaccount',
            name='reward',
            field=models.IntegerField(default=0),
        ),
    ]
