# Generated by Django 2.1.5 on 2019-03-08 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0013_auto_20190307_1352'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Company',
        ),
    ]
