# Generated by Django 2.1.5 on 2019-03-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0014_auto_20190308_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='identifier',
            field=models.CharField(default='', max_length=20),
        ),
    ]
