# Generated by Django 2.1.5 on 2019-03-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0015_company_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
    ]
