# Generated by Django 2.1.5 on 2019-03-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0016_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default='', upload_to='trade/'),
            preserve_default=False,
        ),
    ]
