# Generated by Django 2.1.5 on 2019-03-12 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0018_purchase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carboncoinccy',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-time']},
        ),
        migrations.AlterField(
            model_name='purchase',
            name='company',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trade.Company'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trade.Product'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['user'], name='trade_purch_user_id_14422c_idx'),
        ),
    ]
