# Generated by Django 2.1.5 on 2019-03-21 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0019_auto_20190312_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.IntegerField()),
                ('date', models.DateField()),
                ('ea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.EnergyAccount')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='energyhistory',
            index=models.Index(fields=['ea'], name='trade_energ_ea_id_b1fa16_idx'),
        ),
    ]
